# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Transactions.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Transactions(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1133, 690)
        Form.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 17pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.NavBar = QtWidgets.QWidget(Form)
        self.NavBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setMinimumSize(QtCore.QSize(0, 0))
        self.NavBar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.NavBar.setAutoFillBackground(False)
        self.NavBar.setStyleSheet("")
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NavBarButton = QtWidgets.QPushButton(self.NavBar)
        self.NavBarButton.setStyleSheet("QPushButton {\n"
"    padding: 10px 8px;\n"
"}")
        self.NavBarButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NavBarButton.setIcon(icon)
        self.NavBarButton.setIconSize(QtCore.QSize(35, 35))
        self.NavBarButton.setObjectName("NavBarButton")
        self.verticalLayout.addWidget(self.NavBarButton)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.MainButtons = QtWidgets.QVBoxLayout()
        self.MainButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons.setSpacing(20)
        self.MainButtons.setObjectName("MainButtons")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons.addWidget(self.DashboardButton)
        self.StaffsButton = QtWidgets.QPushButton(self.NavBar)
        self.StaffsButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/user-round-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StaffsButton.setIcon(icon2)
        self.StaffsButton.setIconSize(QtCore.QSize(40, 40))
        self.StaffsButton.setObjectName("StaffsButton")
        self.MainButtons.addWidget(self.StaffsButton)
        self.PatientsButton = QtWidgets.QPushButton(self.NavBar)
        self.PatientsButton.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PatientsButton.setIcon(icon3)
        self.PatientsButton.setIconSize(QtCore.QSize(40, 40))
        self.PatientsButton.setObjectName("PatientsButton")
        self.MainButtons.addWidget(self.PatientsButton)
        self.TransactionsButton = QtWidgets.QPushButton(self.NavBar)
        self.TransactionsButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionsButton.setIcon(icon4)
        self.TransactionsButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionsButton.setObjectName("TransactionsButton")
        self.MainButtons.addWidget(self.TransactionsButton)
        self.ChargesButton = QtWidgets.QPushButton(self.NavBar)
        self.ChargesButton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/hand-coins.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChargesButton.setIcon(icon5)
        self.ChargesButton.setIconSize(QtCore.QSize(40, 40))
        self.ChargesButton.setObjectName("ChargesButton")
        self.MainButtons.addWidget(self.ChargesButton)
        self.verticalLayout.addLayout(self.MainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.SettingButtons = QtWidgets.QVBoxLayout()
        self.SettingButtons.setSpacing(15)
        self.SettingButtons.setObjectName("SettingButtons")
        self.LogOutButton = QtWidgets.QPushButton(self.NavBar)
        self.LogOutButton.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LogOutButton.setIcon(icon6)
        self.LogOutButton.setIconSize(QtCore.QSize(40, 40))
        self.LogOutButton.setObjectName("LogOutButton")
        self.SettingButtons.addWidget(self.LogOutButton, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.SettingButtons)
        self.horizontalLayout_4.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(Form)
        self.MainBodyContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMinimumSize(QtCore.QSize(0, 80))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Header.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InterfaceTitle = QtWidgets.QLabel(self.Header)
        self.InterfaceTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InterfaceTitle.setAlignment(QtCore.Qt.AlignLeading)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_3.addWidget(self.InterfaceTitle)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_3.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_3.addLayout(self.UserPanel)
        self.verticalLayout_2.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 9px; \n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #E0E0E0;  \n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #CCE3D0;\n"
"    color: #2E6E65;\n"
"}\n"
"")
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BodyLayout = QtWidgets.QWidget(self.Body)
        self.BodyLayout.setObjectName("BodyLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.BodyLayout)
        self.verticalLayout_5.setContentsMargins(20, 0, 20, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Buttons = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setMinimumSize(QtCore.QSize(0, 0))
        self.Buttons.setStyleSheet("#SearchBar {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65; \n"
"    border-radius: 15px;\n"
"}\n"
"#Search{\n"
"    background-color: transparent ;\n"
"    font: 300 14pt \"Lexend Light\";\n"
"}\n"
"#AddUserButton {\n"
"    padding: 0px 30px;\n"
"    text-align: center;\n"
"}\n"
"QComboBox {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/lucide/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;  \n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"")
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchBar = QtWidgets.QWidget(self.Buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBar.sizePolicy().hasHeightForWidth())
        self.SearchBar.setSizePolicy(sizePolicy)
        self.SearchBar.setMinimumSize(QtCore.QSize(290, 0))
        self.SearchBar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SearchBar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Search = QtWidgets.QLineEdit(self.SearchBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search.sizePolicy().hasHeightForWidth())
        self.Search.setSizePolicy(sizePolicy)
        self.Search.setObjectName("Search")
        self.horizontalLayout_2.addWidget(self.Search)
        self.SearchIcon = QtWidgets.QPushButton(self.SearchBar)
        self.SearchIcon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchIcon.setIcon(icon7)
        self.SearchIcon.setIconSize(QtCore.QSize(35, 35))
        self.SearchIcon.setObjectName("SearchIcon")
        self.horizontalLayout_2.addWidget(self.SearchIcon)
        self.horizontalLayout.addWidget(self.SearchBar)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.Buttons, 0, QtCore.Qt.AlignTop)
        self.Transaction = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Transaction.sizePolicy().hasHeightForWidth())
        self.Transaction.setSizePolicy(sizePolicy)
        self.Transaction.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.Transaction.setObjectName("Transaction")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Transaction)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.Transaction)
        self.scrollArea.setStyleSheet("QScrollBar:vertical{\n"
"     background: transparent;\n"
"     width: 10px;\n"
"     border-radius: 5px;\n"
"}\n"
"QScrollBar:horizontal  {\n"
"     background: transparent;\n"
"     height: 10px;\n"
"     border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal  {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:horizontal{\n"
"        background: none;\n"
"        border: none;\n"
"}\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 676, 513))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.TransactionTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TransactionTable.setFont(font)
        self.TransactionTable.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font: 16pt \"Lexend\";\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 18px \"Lexend Medium\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.TransactionTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TransactionTable.setCornerButtonEnabled(True)
        self.TransactionTable.setColumnCount(4)
        self.TransactionTable.setObjectName("TransactionTable")
        self.TransactionTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TransactionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TransactionTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TransactionTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TransactionTable.setHorizontalHeaderItem(3, item)
        self.TransactionTable.horizontalHeader().setHighlightSections(True)
        self.TransactionTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.TransactionTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.widget = QtWidgets.QWidget(self.Transaction)
        self.widget.setMinimumSize(QtCore.QSize(110, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ViewTransaction = QtWidgets.QPushButton(self.widget)
        self.ViewTransaction.setObjectName("ViewTransaction")
        self.verticalLayout_6.addWidget(self.ViewTransaction)
        self.horizontalLayout_5.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.Transaction)
        self.verticalLayout_4.addWidget(self.BodyLayout)
        self.verticalLayout_2.addWidget(self.Body)
        self.horizontalLayout_4.addWidget(self.MainBodyContainer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.NavBarButton.setToolTip(_translate("Form", "View Main Dashboard"))
        self.DashboardButton.setToolTip(_translate("Form", "View Main Dashboard"))
        self.DashboardButton.setText(_translate("Form", " Dashboard"))
        self.StaffsButton.setToolTip(_translate("Form", "View Staff Record"))
        self.StaffsButton.setText(_translate("Form", " Staffs"))
        self.PatientsButton.setToolTip(_translate("Form", "View Patient Record"))
        self.PatientsButton.setText(_translate("Form", " Records"))
        self.TransactionsButton.setToolTip(_translate("Form", "View Transactions "))
        self.TransactionsButton.setText(_translate("Form", " Transactions"))
        self.ChargesButton.setToolTip(_translate("Form", "View Reports and Overviews"))
        self.ChargesButton.setText(_translate("Form", " Charges"))
        self.LogOutButton.setToolTip(_translate("Form", "Log Out from your Account"))
        self.LogOutButton.setText(_translate("Form", " Log Out"))
        self.InterfaceTitle.setText(_translate("Form", "Transactions"))
        self.UserName.setText(_translate("Form", "ADMIN"))
        item = self.TransactionTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Transaction ID"))
        item = self.TransactionTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.TransactionTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Diagnosis"))
        item = self.TransactionTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Transaction Date"))
        self.ViewTransaction.setText(_translate("Form", "View"))
