# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Staffs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Images import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1150, 805)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(1150, 805))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65; \n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.NavBar = QtWidgets.QWidget(self.centralwidget)
        self.NavBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setMinimumSize(QtCore.QSize(0, 0))
        self.NavBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NavBar.setAutoFillBackground(False)
        self.NavBar.setStyleSheet("")
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DashboardButton_2 = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton_2.setStyleSheet("QPushButton {\n"
"    padding: 10px 8px;\n"
"}")
        self.DashboardButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lucide/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton_2.setIcon(icon)
        self.DashboardButton_2.setIconSize(QtCore.QSize(35, 35))
        self.DashboardButton_2.setObjectName("DashboardButton_2")
        self.verticalLayout.addWidget(self.DashboardButton_2)
        self.label_3 = QtWidgets.QLabel(self.NavBar)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.MainButtons = QtWidgets.QVBoxLayout()
        self.MainButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons.setSpacing(20)
        self.MainButtons.setObjectName("MainButtons")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/lucide/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(20, 20))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons.addWidget(self.DashboardButton)
        self.PatientsButton = QtWidgets.QPushButton(self.NavBar)
        self.PatientsButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/lucide/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PatientsButton.setIcon(icon2)
        self.PatientsButton.setIconSize(QtCore.QSize(40, 40))
        self.PatientsButton.setObjectName("PatientsButton")
        self.MainButtons.addWidget(self.PatientsButton)
        self.StaffButton = QtWidgets.QPushButton(self.NavBar)
        self.StaffButton.setStyleSheet("QPushButton{\n"
"     border: 3px solid white;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StaffButton.setIcon(icon3)
        self.StaffButton.setIconSize(QtCore.QSize(40, 40))
        self.StaffButton.setObjectName("StaffButton")
        self.MainButtons.addWidget(self.StaffButton)
        self.TransactionsButton = QtWidgets.QPushButton(self.NavBar)
        self.TransactionsButton.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/lucide/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionsButton.setIcon(icon4)
        self.TransactionsButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionsButton.setObjectName("TransactionsButton")
        self.MainButtons.addWidget(self.TransactionsButton)
        self.ChargesButton = QtWidgets.QPushButton(self.NavBar)
        self.ChargesButton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/lucide/icons/chart-no-axes-combined.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChargesButton.setIcon(icon5)
        self.ChargesButton.setIconSize(QtCore.QSize(40, 40))
        self.ChargesButton.setObjectName("ChargesButton")
        self.MainButtons.addWidget(self.ChargesButton)
        self.verticalLayout.addLayout(self.MainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.SettingButtons = QtWidgets.QVBoxLayout()
        self.SettingButtons.setSpacing(15)
        self.SettingButtons.setObjectName("SettingButtons")
        self.OverviewsButton_3 = QtWidgets.QPushButton(self.NavBar)
        self.OverviewsButton_3.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/lucide/icons/user-round-cog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OverviewsButton_3.setIcon(icon6)
        self.OverviewsButton_3.setIconSize(QtCore.QSize(40, 40))
        self.OverviewsButton_3.setObjectName("OverviewsButton_3")
        self.SettingButtons.addWidget(self.OverviewsButton_3)
        self.OverviewsButton_2 = QtWidgets.QPushButton(self.NavBar)
        self.OverviewsButton_2.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/lucide/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OverviewsButton_2.setIcon(icon7)
        self.OverviewsButton_2.setIconSize(QtCore.QSize(40, 40))
        self.OverviewsButton_2.setObjectName("OverviewsButton_2")
        self.SettingButtons.addWidget(self.OverviewsButton_2, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.SettingButtons)
        self.horizontalLayout_4.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(self.centralwidget)
        self.MainBodyContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMinimumSize(QtCore.QSize(0, 80))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Header.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InterfaceTitle = QtWidgets.QLabel(self.Header)
        self.InterfaceTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InterfaceTitle.setAlignment(QtCore.Qt.AlignLeading)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_3.addWidget(self.InterfaceTitle)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_3.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_3.addLayout(self.UserPanel)
        self.verticalLayout_2.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 9px; \n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #E0E0E0;  \n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #CCE3D0;\n"
"    color: #2E6E65;\n"
"}\n"
"")
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BodyLayout = QtWidgets.QWidget(self.Body)
        self.BodyLayout.setObjectName("BodyLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.BodyLayout)
        self.verticalLayout_5.setContentsMargins(20, 0, 20, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Buttons = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Buttons.sizePolicy().hasHeightForWidth())
        self.Buttons.setSizePolicy(sizePolicy)
        self.Buttons.setMinimumSize(QtCore.QSize(0, 0))
        self.Buttons.setStyleSheet("#SearchBar {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65; \n"
"    border-radius: 15px;\n"
"}\n"
"#Search{\n"
"    background-color: transparent ;\n"
"    font: 300 14pt \"Lexend Light\";\n"
"}\n"
"#AddUserButton {\n"
"    text-align: center;\n"
"}\n"
"QComboBox {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/lucide/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;  \n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"\n"
"")
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchBar = QtWidgets.QWidget(self.Buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBar.sizePolicy().hasHeightForWidth())
        self.SearchBar.setSizePolicy(sizePolicy)
        self.SearchBar.setMinimumSize(QtCore.QSize(290, 0))
        self.SearchBar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SearchBar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Icon = QtWidgets.QPushButton(self.SearchBar)
        self.Icon.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/lucide/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon8)
        self.Icon.setIconSize(QtCore.QSize(30, 30))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_2.addWidget(self.Icon)
        self.Search = QtWidgets.QLineEdit(self.SearchBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search.sizePolicy().hasHeightForWidth())
        self.Search.setSizePolicy(sizePolicy)
        self.Search.setObjectName("Search")
        self.horizontalLayout_2.addWidget(self.Search)
        self.horizontalLayout.addWidget(self.SearchBar)
        self.Specialty = QtWidgets.QComboBox(self.Buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Specialty.sizePolicy().hasHeightForWidth())
        self.Specialty.setSizePolicy(sizePolicy)
        self.Specialty.setMinimumSize(QtCore.QSize(0, 0))
        self.Specialty.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Specialty.setObjectName("Specialty")
        self.Specialty.addItem("")
        self.Specialty.addItem("")
        self.Specialty.addItem("")
        self.horizontalLayout.addWidget(self.Specialty)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.AddUserButton = QtWidgets.QPushButton(self.Buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddUserButton.sizePolicy().hasHeightForWidth())
        self.AddUserButton.setSizePolicy(sizePolicy)
        self.AddUserButton.setMinimumSize(QtCore.QSize(0, 45))
        self.AddUserButton.setMaximumSize(QtCore.QSize(200, 45))
        self.AddUserButton.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"}")
        self.AddUserButton.setObjectName("AddUserButton")
        self.horizontalLayout.addWidget(self.AddUserButton)
        self.verticalLayout_5.addWidget(self.Buttons, 0, QtCore.Qt.AlignTop)
        self.Doctor = QtWidgets.QWidget(self.BodyLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Doctor.sizePolicy().hasHeightForWidth())
        self.Doctor.setSizePolicy(sizePolicy)
        self.Doctor.setObjectName("Doctor")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Doctor)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.Doctor)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.DoctorTable = QtWidgets.QTableWidget(self.Doctor)
        self.DoctorTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.DoctorTable.setCornerButtonEnabled(True)
        self.DoctorTable.setColumnCount(3)
        self.DoctorTable.setObjectName("DoctorTable")
        self.DoctorTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DoctorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoctorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoctorTable.setHorizontalHeaderItem(2, item)
        self.DoctorTable.horizontalHeader().setHighlightSections(True)
        self.DoctorTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.DoctorTable)
        self.verticalLayout_5.addWidget(self.Doctor)
        self.Staff = QtWidgets.QWidget(self.BodyLayout)
        self.Staff.setObjectName("Staff")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Staff)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.Staff)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.StaffTable = QtWidgets.QTableWidget(self.Staff)
        self.StaffTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StaffTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.StaffTable.setColumnCount(2)
        self.StaffTable.setObjectName("StaffTable")
        self.StaffTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.StaffTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.StaffTable.setHorizontalHeaderItem(1, item)
        self.StaffTable.horizontalHeader().setCascadingSectionResizes(True)
        self.StaffTable.horizontalHeader().setHighlightSections(True)
        self.StaffTable.horizontalHeader().setSortIndicatorShown(False)
        self.StaffTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.StaffTable)
        self.verticalLayout_5.addWidget(self.Staff)
        self.verticalLayout_4.addWidget(self.BodyLayout)
        self.verticalLayout_2.addWidget(self.Body)
        self.horizontalLayout_4.addWidget(self.MainBodyContainer)
        self.MainBodyContainer.raise_()
        self.NavBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DashboardButton_2.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.DashboardButton.setToolTip(_translate("MainWindow", "View Main Dashboard"))
        self.DashboardButton.setText(_translate("MainWindow", "  Dashboard"))
        self.PatientsButton.setToolTip(_translate("MainWindow", "View Patient Record"))
        self.PatientsButton.setText(_translate("MainWindow", "  Records"))
        self.StaffButton.setToolTip(_translate("MainWindow", "View Staff Record"))
        self.StaffButton.setText(_translate("MainWindow", "  Staffs"))
        self.TransactionsButton.setToolTip(_translate("MainWindow", "View Transactions "))
        self.TransactionsButton.setText(_translate("MainWindow", "  Transactions"))
        self.ChargesButton.setToolTip(_translate("MainWindow", "View Reports and Overviews"))
        self.ChargesButton.setText(_translate("MainWindow", "Charges"))
        self.OverviewsButton_3.setToolTip(_translate("MainWindow", "View Profile Settings"))
        self.OverviewsButton_3.setText(_translate("MainWindow", "  Profile"))
        self.OverviewsButton_2.setToolTip(_translate("MainWindow", "Log Out from your Account"))
        self.OverviewsButton_2.setText(_translate("MainWindow", "  Log Out"))
        self.InterfaceTitle.setText(_translate("MainWindow", "Staffs"))
        self.UserName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("MainWindow", "Admin"))
        self.Specialty.setItemText(0, _translate("MainWindow", "Gynecologist"))
        self.Specialty.setItemText(1, _translate("MainWindow", "Pediatrician"))
        self.Specialty.setItemText(2, _translate("MainWindow", "Opthalmologist"))
        self.AddUserButton.setText(_translate("MainWindow", "Add User"))
        self.label.setText(_translate("MainWindow", "Doctors"))
        item = self.DoctorTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Doctor ID"))
        item = self.DoctorTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.DoctorTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Specialty"))
        self.label_2.setText(_translate("MainWindow", "Staff"))
        item = self.StaffTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Staff ID"))
        item = self.StaffTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
