# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_TransactionDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1150, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(1150, 560))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 16pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65; \n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.MainBodyContainer = QtWidgets.QFrame(self.centralwidget)
        self.MainBodyContainer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMinimumSize(QtCore.QSize(0, 80))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Header.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BackButtonCon = QtWidgets.QWidget(self.Header)
        self.BackButtonCon.setStyleSheet("#Title{\n"
"    font: 700 22pt \"Lexend\";\n"
"}\n"
"#Subtitle {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"")
        self.BackButtonCon.setObjectName("BackButtonCon")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BackButtonCon)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.BackButtonCon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(0, 30))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setAlignment(QtCore.Qt.AlignLeading)
        self.Title.setWordWrap(True)
        self.Title.setObjectName("Title")
        self.verticalLayout_5.addWidget(self.Title, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.BackButtonCon, 0, QtCore.Qt.AlignTop)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignVCenter)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_3.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_3.addLayout(self.UserPanel)
        self.verticalLayout_2.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.Body = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 9px; \n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #E0E0E0;  \n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: bold 14px \"Segoe UI\";\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #CCE3D0;\n"
"    color: #2E6E65;\n"
"}\n"
"")
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_4.setContentsMargins(20, 10, 20, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BodyLayout = QtWidgets.QWidget(self.Body)
        self.BodyLayout.setObjectName("BodyLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.BodyLayout)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Transaction = QtWidgets.QWidget(self.BodyLayout)
        self.Transaction.setMinimumSize(QtCore.QSize(0, 30))
        self.Transaction.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Transaction.setStyleSheet("QLabel {\n"
"    color: #2B3752;\n"
"    font: 11pt \"Lexend\";\n"
"}\n"
"#PatientID, #PatientName, #PatientAge, #PatientGender, #DoctorID,  #DoctorName,  #DoctorSpecialty, #StaffID, #StaffName, #TransactionDate, #TransactionID, #TransactionTime, #TransactionFee, #Diagnosis, #Notes  {\n"
"    font: 700 14pt \"Lexend\";\n"
"}\n"
"#Transaction {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65 ;\n"
"    border-radius: 15px;\n"
"}\n"
"#Doctor, #Patient, #Staff {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"    border-radius: 10px;\n"
"}")
        self.Transaction.setObjectName("Transaction")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Transaction)
        self.verticalLayout_7.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.Transaction)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.Patient = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Patient.sizePolicy().hasHeightForWidth())
        self.Patient.setSizePolicy(sizePolicy)
        self.Patient.setObjectName("Patient")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.Patient)
        self.verticalLayout_18.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_18.setSpacing(10)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_19 = QtWidgets.QWidget(self.Patient)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_7 = QtWidgets.QLabel(self.widget_19)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_24.addWidget(self.label_7)
        self.PatientID = QtWidgets.QLabel(self.widget_19)
        self.PatientID.setObjectName("PatientID")
        self.verticalLayout_24.addWidget(self.PatientID)
        self.verticalLayout_18.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.Patient)
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(1)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_9 = QtWidgets.QLabel(self.widget_20)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_27.addWidget(self.label_9)
        self.PatientName = QtWidgets.QLabel(self.widget_20)
        self.PatientName.setObjectName("PatientName")
        self.verticalLayout_27.addWidget(self.PatientName)
        self.verticalLayout_18.addWidget(self.widget_20)
        self.widget_21 = QtWidgets.QWidget(self.Patient)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_28 = QtWidgets.QWidget(self.widget_21)
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(1)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_11 = QtWidgets.QLabel(self.widget_28)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_26.addWidget(self.label_11)
        self.PatientGender = QtWidgets.QLabel(self.widget_28)
        self.PatientGender.setObjectName("PatientGender")
        self.verticalLayout_26.addWidget(self.PatientGender)
        self.horizontalLayout_6.addWidget(self.widget_28)
        self.widget_29 = QtWidgets.QWidget(self.widget_21)
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(1)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_13 = QtWidgets.QLabel(self.widget_29)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_25.addWidget(self.label_13)
        self.PatientAge = QtWidgets.QLabel(self.widget_29)
        self.PatientAge.setObjectName("PatientAge")
        self.verticalLayout_25.addWidget(self.PatientAge)
        self.horizontalLayout_6.addWidget(self.widget_29)
        self.verticalLayout_18.addWidget(self.widget_21)
        self.verticalLayout_8.addWidget(self.Patient)
        self.horizontalLayout_2.addWidget(self.widget_4, 0, QtCore.Qt.AlignTop)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.Doctor = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Doctor.sizePolicy().hasHeightForWidth())
        self.Doctor.setSizePolicy(sizePolicy)
        self.Doctor.setObjectName("Doctor")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.Doctor)
        self.verticalLayout_17.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_22 = QtWidgets.QWidget(self.Doctor)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.widget_22)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.DoctorID = QtWidgets.QLabel(self.widget_22)
        self.DoctorID.setObjectName("DoctorID")
        self.verticalLayout_21.addWidget(self.DoctorID)
        self.verticalLayout_17.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.Doctor)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(1)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.widget_23)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_22.addWidget(self.label_18)
        self.DoctorName = QtWidgets.QLabel(self.widget_23)
        self.DoctorName.setObjectName("DoctorName")
        self.verticalLayout_22.addWidget(self.DoctorName)
        self.verticalLayout_17.addWidget(self.widget_23)
        self.widget_24 = QtWidgets.QWidget(self.Doctor)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_19 = QtWidgets.QLabel(self.widget_24)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_23.addWidget(self.label_19)
        self.DoctorSpecialty = QtWidgets.QLabel(self.widget_24)
        self.DoctorSpecialty.setObjectName("DoctorSpecialty")
        self.verticalLayout_23.addWidget(self.DoctorSpecialty)
        self.verticalLayout_17.addWidget(self.widget_24)
        self.verticalLayout_9.addWidget(self.Doctor)
        self.horizontalLayout_2.addWidget(self.widget_5, 0, QtCore.Qt.AlignTop)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.Staff = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Staff.sizePolicy().hasHeightForWidth())
        self.Staff.setSizePolicy(sizePolicy)
        self.Staff.setObjectName("Staff")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Staff)
        self.verticalLayout_16.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_25 = QtWidgets.QWidget(self.Staff)
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_21 = QtWidgets.QLabel(self.widget_25)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_19.addWidget(self.label_21)
        self.StaffID = QtWidgets.QLabel(self.widget_25)
        self.StaffID.setObjectName("StaffID")
        self.verticalLayout_19.addWidget(self.StaffID)
        self.verticalLayout_16.addWidget(self.widget_25, 0, QtCore.Qt.AlignTop)
        self.widget_26 = QtWidgets.QWidget(self.Staff)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_23 = QtWidgets.QLabel(self.widget_26)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_20.addWidget(self.label_23)
        self.StaffName = QtWidgets.QLabel(self.widget_26)
        self.StaffName.setObjectName("StaffName")
        self.verticalLayout_20.addWidget(self.StaffName)
        self.verticalLayout_16.addWidget(self.widget_26, 0, QtCore.Qt.AlignTop)
        self.widget_27 = QtWidgets.QWidget(self.Staff)
        self.widget_27.setObjectName("widget_27")
        self.verticalLayout_16.addWidget(self.widget_27)
        self.verticalLayout_10.addWidget(self.Staff)
        self.horizontalLayout_2.addWidget(self.widget_6, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.Transaction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_31 = QtWidgets.QWidget(self.widget_3)
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(10)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widget_33 = QtWidgets.QWidget(self.widget_31)
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.widget_33)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(1)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_8 = QtWidgets.QLabel(self.widget_33)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_35.addWidget(self.label_8)
        self.Diagnosis = QtWidgets.QLabel(self.widget_33)
        self.Diagnosis.setObjectName("Diagnosis")
        self.verticalLayout_35.addWidget(self.Diagnosis)
        self.verticalLayout_30.addWidget(self.widget_33, 0, QtCore.Qt.AlignTop)
        self.widget_34 = QtWidgets.QWidget(self.widget_31)
        self.widget_34.setObjectName("widget_34")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.widget_34)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(1)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_16 = QtWidgets.QLabel(self.widget_34)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_36.addWidget(self.label_16)
        self.ViewDiagnosis = QtWidgets.QPushButton(self.widget_34)
        self.ViewDiagnosis.setStyleSheet("#ViewDiagnosis {\n"
"    font: 900 13pt \"Satoshi Black\";\n"
"    background-color: #2E6E65;\n"
"     border-radius: 14px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"    padding: 4px 20px;\n"
"}")
        self.ViewDiagnosis.setObjectName("ViewDiagnosis")
        self.verticalLayout_36.addWidget(self.ViewDiagnosis, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_30.addWidget(self.widget_34, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.widget_31)
        self.widget_30 = QtWidgets.QWidget(self.widget_3)
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(10)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.widget_36 = QtWidgets.QWidget(self.widget_30)
        self.widget_36.setObjectName("widget_36")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.widget_36)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(1)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_20 = QtWidgets.QLabel(self.widget_36)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_31.addWidget(self.label_20)
        self.TransactionDate = QtWidgets.QLabel(self.widget_36)
        self.TransactionDate.setObjectName("TransactionDate")
        self.verticalLayout_31.addWidget(self.TransactionDate)
        self.verticalLayout_29.addWidget(self.widget_36, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.widget_30)
        self.widget_32 = QtWidgets.QWidget(self.widget_3)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.widget_32)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(10)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.widget_37 = QtWidgets.QWidget(self.widget_32)
        self.widget_37.setObjectName("widget_37")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.widget_37)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(1)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_26 = QtWidgets.QLabel(self.widget_37)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_34.addWidget(self.label_26)
        self.TransactionID = QtWidgets.QLabel(self.widget_37)
        self.TransactionID.setObjectName("TransactionID")
        self.verticalLayout_34.addWidget(self.TransactionID)
        self.verticalLayout_28.addWidget(self.widget_37, 0, QtCore.Qt.AlignTop)
        self.widget_38 = QtWidgets.QWidget(self.widget_32)
        self.widget_38.setObjectName("widget_38")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.widget_38)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(1)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_28 = QtWidgets.QLabel(self.widget_38)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_33.addWidget(self.label_28)
        self.TransactionFee = QtWidgets.QLabel(self.widget_38)
        self.TransactionFee.setObjectName("TransactionFee")
        self.verticalLayout_33.addWidget(self.TransactionFee)
        self.verticalLayout_28.addWidget(self.widget_38, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.widget_32)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.verticalLayout_6.addWidget(self.Transaction, 0, QtCore.Qt.AlignTop)
        self.widget_10 = QtWidgets.QWidget(self.BodyLayout)
        self.widget_10.setStyleSheet("#PatGenInfo, #HistoryCon {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"QLabel {\n"
"    color: #2B3752;\n"
"    font: 10pt \"Lexend\";\n"
"}\n"
"#TransactionID_2, #Diagnosis_2, #TransactionDate_2, #Transactor, #DiagnosedBy {\n"
"    font: 500 14pt \"Lexend\";\n"
"}\n"
"\n"
"#Header_2 {\n"
"    color: #2E6E65;\n"
"    font: 700 15pt \"Lexend\";\n"
"}\n"
"#HistoryObject {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_6.addWidget(self.widget_10, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.BodyLayout, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.Body)
        self.horizontalLayout_4.addWidget(self.MainBodyContainer, 0, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Transaction Details"))
        self.UserName.setText(_translate("MainWindow", "ADMIN"))
        self.label_3.setText(_translate("MainWindow", "Patient Info"))
        self.label_7.setText(_translate("MainWindow", "Patient ID"))
        self.PatientID.setText(_translate("MainWindow", "10000004"))
        self.label_9.setText(_translate("MainWindow", "Patient Name"))
        self.PatientName.setText(_translate("MainWindow", "Roy Adrian Rondina"))
        self.label_11.setText(_translate("MainWindow", "Gender"))
        self.PatientGender.setText(_translate("MainWindow", "Male"))
        self.label_13.setText(_translate("MainWindow", "Age"))
        self.PatientAge.setText(_translate("MainWindow", "17"))
        self.label_2.setText(_translate("MainWindow", "Doctor Info"))
        self.label_15.setText(_translate("MainWindow", "Doctor ID"))
        self.DoctorID.setText(_translate("MainWindow", "10005"))
        self.label_18.setText(_translate("MainWindow", "Doctor Name"))
        self.DoctorName.setText(_translate("MainWindow", "Dr. Jayson Gabriel"))
        self.label_19.setText(_translate("MainWindow", "Specialty"))
        self.DoctorSpecialty.setText(_translate("MainWindow", "Ophthalmologist"))
        self.label.setText(_translate("MainWindow", "Transactor Info"))
        self.label_21.setText(_translate("MainWindow", "Staff ID"))
        self.StaffID.setText(_translate("MainWindow", "1000007"))
        self.label_23.setText(_translate("MainWindow", "Staff Name"))
        self.StaffName.setText(_translate("MainWindow", "Dan Bejec"))
        self.label_8.setText(_translate("MainWindow", "Diagnosis"))
        self.Diagnosis.setText(_translate("MainWindow", "Fever"))
        self.label_16.setText(_translate("MainWindow", "See Diagnosis"))
        self.ViewDiagnosis.setText(_translate("MainWindow", "View Diagnosis"))
        self.label_20.setText(_translate("MainWindow", "Transaction Date"))
        self.TransactionDate.setText(_translate("MainWindow", "December 12, 2024"))
        self.label_26.setText(_translate("MainWindow", "Transaction ID"))
        self.TransactionID.setText(_translate("MainWindow", "121224-001"))
        self.label_28.setText(_translate("MainWindow", "Transaction Fee"))
        self.TransactionFee.setText(_translate("MainWindow", "₱ 200"))
