# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doctor_Diagnosis.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Doctor_Diagnosis(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 772)
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"#User, #UserSpecialty {\n"
"    color: #F4F7ED;\n"
"}\n"
"#DoctorSidePanel {\n"
"     background-color: #2E6E65;\n"
"}\n"
"\n"
"#RecentText {\n"
"    color: #F4F7ED;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"#Header {\n"
"    padding: 10px 20px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px;\n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 40px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 25px;\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2E6E65;\n"
"    font-size: 15px;\n"
"    color: #1b3b3a;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        self.Header.setStyleSheet("QLabel {\n"
"    font: bold 20pt \"Satoshi Black\";\n"
"    color: #2E6E65;\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"#Subheader {\n"
"    font: 500 14pt \"Satoshi Medium\";\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Header)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(self.Header)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.Subheader = QtWidgets.QLabel(self.Header)
        self.Subheader.setObjectName("Subheader")
        self.verticalLayout.addWidget(self.Subheader)
        self.verticalLayout_2.addWidget(self.Header)
        self.MainBody = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setStyleSheet("#Info {\n"
"    background-color: #b5cecb;\n"
"     border: 1px solid #2E6E65;\n"
"    /*border-radius: 20px;*/\n"
"}\n"
"QLabel {\n"
"    font: 500 13pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"#PatName, #PatID, #Dob, #PatGender, #Age, #PatStatus, #CheckID {\n"
"    font: 900 16pt \"Satoshi\";\n"
"}\n"
"\n"
"#Type {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#Info {\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"#PatRecord {\n"
"     border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"#LabReq {\n"
"    border: 1px solid #2E6E65;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"#BPLabel_2, #BPInfo_2,\n"
"#TempLabel_2, #TempInfo_2,\n"
"#WeightLabel_2, #WeightInfo_2,\n"
"#HeightLabel_2, #HeightInfo_2 {\n"
"    font-size: 17px;\n"
"    font-weight: 300;\n"
"    color: #2b3752;\n"
"}\n"
"")
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_5.setContentsMargins(20, -1, 20, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Info = QtWidgets.QFrame(self.MainBody)
        self.Info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Info.setObjectName("Info")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Info)
        self.horizontalLayout_10.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PatInfo = QtWidgets.QFrame(self.Info)
        self.PatInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatInfo.setObjectName("PatInfo")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.PatInfo)
        self.verticalLayout_6.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget = QtWidgets.QWidget(self.PatInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label = QtWidgets.QLabel(self.widget)
        self.Label.setObjectName("Label")
        self.verticalLayout_3.addWidget(self.Label)
        self.PatID = QtWidgets.QLabel(self.widget)
        self.PatID.setObjectName("PatID")
        self.verticalLayout_3.addWidget(self.PatID)
        self.horizontalLayout_9.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.PatInfo)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label_2 = QtWidgets.QLabel(self.widget_2)
        self.Label_2.setObjectName("Label_2")
        self.verticalLayout_4.addWidget(self.Label_2)
        self.PatName = QtWidgets.QLabel(self.widget_2)
        self.PatName.setObjectName("PatName")
        self.verticalLayout_4.addWidget(self.PatName)
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.frame_11 = QtWidgets.QFrame(self.PatInfo)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(25)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.DOB = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DOB.sizePolicy().hasHeightForWidth())
        self.DOB.setSizePolicy(sizePolicy)
        self.DOB.setMinimumSize(QtCore.QSize(189, 0))
        self.DOB.setStyleSheet("")
        self.DOB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DOB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DOB.setObjectName("DOB")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.DOB)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_3 = QtWidgets.QLabel(self.DOB)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_20.addWidget(self.label_3)
        self.Dob = QtWidgets.QLabel(self.DOB)
        self.Dob.setObjectName("Dob")
        self.verticalLayout_20.addWidget(self.Dob)
        self.horizontalLayout_8.addWidget(self.DOB)
        self.PatAge = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatAge.sizePolicy().hasHeightForWidth())
        self.PatAge.setSizePolicy(sizePolicy)
        self.PatAge.setStyleSheet("")
        self.PatAge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatAge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatAge.setObjectName("PatAge")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.PatAge)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label = QtWidgets.QLabel(self.PatAge)
        self.label.setObjectName("label")
        self.verticalLayout_19.addWidget(self.label)
        self.Age = QtWidgets.QLabel(self.PatAge)
        self.Age.setObjectName("Age")
        self.verticalLayout_19.addWidget(self.Age)
        self.horizontalLayout_8.addWidget(self.PatAge)
        self.PatDOB_2 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatDOB_2.sizePolicy().hasHeightForWidth())
        self.PatDOB_2.setSizePolicy(sizePolicy)
        self.PatDOB_2.setStyleSheet("")
        self.PatDOB_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatDOB_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatDOB_2.setObjectName("PatDOB_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.PatDOB_2)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_4 = QtWidgets.QLabel(self.PatDOB_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_21.addWidget(self.label_4)
        self.PatGender = QtWidgets.QLabel(self.PatDOB_2)
        self.PatGender.setObjectName("PatGender")
        self.verticalLayout_21.addWidget(self.PatGender)
        self.horizontalLayout_8.addWidget(self.PatDOB_2)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.horizontalLayout_10.addWidget(self.PatInfo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.widget_4 = QtWidgets.QWidget(self.Info)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status = QtWidgets.QFrame(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status.setObjectName("status")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.status)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.weg = QtWidgets.QLabel(self.status)
        self.weg.setObjectName("weg")
        self.verticalLayout_17.addWidget(self.weg)
        self.CheckID = QtWidgets.QLabel(self.status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckID.sizePolicy().hasHeightForWidth())
        self.CheckID.setSizePolicy(sizePolicy)
        self.CheckID.setAlignment(QtCore.Qt.AlignLeading)
        self.CheckID.setObjectName("CheckID")
        self.verticalLayout_17.addWidget(self.CheckID, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.status, 0, QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(1)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.Type_2 = QtWidgets.QLabel(self.widget_3)
        self.Type_2.setObjectName("Type_2")
        self.verticalLayout_22.addWidget(self.Type_2)
        self.Type = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Type.sizePolicy().hasHeightForWidth())
        self.Type.setSizePolicy(sizePolicy)
        self.Type.setAlignment(QtCore.Qt.AlignLeading)
        self.Type.setObjectName("Type")
        self.verticalLayout_22.addWidget(self.Type)
        self.horizontalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_10.addWidget(self.widget_4)
        self.verticalLayout_5.addWidget(self.Info)
        self.PatRecord = QtWidgets.QFrame(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatRecord.sizePolicy().hasHeightForWidth())
        self.PatRecord.setSizePolicy(sizePolicy)
        self.PatRecord.setStyleSheet("QLabel {\n"
"    font: 700 14pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}")
        self.PatRecord.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatRecord.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatRecord.setObjectName("PatRecord")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.PatRecord)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PatDetails = QtWidgets.QFrame(self.PatRecord)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatDetails.sizePolicy().hasHeightForWidth())
        self.PatDetails.setSizePolicy(sizePolicy)
        self.PatDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PatDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PatDetails.setObjectName("PatDetails")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.PatDetails)
        self.horizontalLayout_4.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.PatDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.BPLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.BPLabel_2.setObjectName("BPLabel_2")
        self.verticalLayout_8.addWidget(self.BPLabel_2)
        self.TempLabel_2 = QtWidgets.QLabel(self.frame_5)
        self.TempLabel_2.setObjectName("TempLabel_2")
        self.verticalLayout_8.addWidget(self.TempLabel_2)
        self.horizontalLayout_6.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.BP = QtWidgets.QLabel(self.frame_6)
        self.BP.setObjectName("BP")
        self.verticalLayout_9.addWidget(self.BP)
        self.Temperature = QtWidgets.QLabel(self.frame_6)
        self.Temperature.setObjectName("Temperature")
        self.verticalLayout_9.addWidget(self.Temperature)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.PatDetails)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.WeightLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.WeightLabel_2.setObjectName("WeightLabel_2")
        self.verticalLayout_10.addWidget(self.WeightLabel_2)
        self.HeightLabel_2 = QtWidgets.QLabel(self.frame_7)
        self.HeightLabel_2.setObjectName("HeightLabel_2")
        self.verticalLayout_10.addWidget(self.HeightLabel_2)
        self.horizontalLayout_7.addWidget(self.frame_7, 0, QtCore.Qt.AlignLeft)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Weight = QtWidgets.QLabel(self.frame_8)
        self.Weight.setObjectName("Weight")
        self.verticalLayout_11.addWidget(self.Weight)
        self.Height = QtWidgets.QLabel(self.frame_8)
        self.Height.setObjectName("Height")
        self.verticalLayout_11.addWidget(self.Height)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_7.addWidget(self.PatDetails)
        self.verticalLayout_5.addWidget(self.PatRecord)
        self.LabReq = QtWidgets.QFrame(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabReq.sizePolicy().hasHeightForWidth())
        self.LabReq.setSizePolicy(sizePolicy)
        self.LabReq.setStyleSheet("QLabel {\n"
"    font: 700 14pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"\n"
"#BPLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#BPInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#AgeLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#AgeInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#GenderLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#GenderInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#WeightLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#WeightInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#HeightLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#HeightInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#TempLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"#TempInfo {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#ProceedButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#OtherText {\n"
"    border: none;\n"
"    border-bottom: 2px solid #2b3752;\n"
"    background: transparent;\n"
"    color: #2b3752;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"")
        self.LabReq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LabReq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LabReq.setObjectName("LabReq")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.LabReq)
        self.verticalLayout_12.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Header_2 = QtWidgets.QFrame(self.LabReq)
        self.Header_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header_2.setObjectName("Header_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Header_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.LabLabel = QtWidgets.QLabel(self.Header_2)
        self.LabLabel.setObjectName("LabLabel")
        self.verticalLayout_13.addWidget(self.LabLabel)
        self.verticalLayout_12.addWidget(self.Header_2)
        self.LabDetails = QtWidgets.QFrame(self.LabReq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabDetails.sizePolicy().hasHeightForWidth())
        self.LabDetails.setSizePolicy(sizePolicy)
        self.LabDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LabDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LabDetails.setObjectName("LabDetails")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.LabDetails)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.FirstFrame = QtWidgets.QFrame(self.LabDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FirstFrame.sizePolicy().hasHeightForWidth())
        self.FirstFrame.setSizePolicy(sizePolicy)
        self.FirstFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FirstFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FirstFrame.setObjectName("FirstFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.FirstFrame)
        self.verticalLayout_14.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5.addWidget(self.FirstFrame)
        self.SecondFrame = QtWidgets.QFrame(self.LabDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SecondFrame.sizePolicy().hasHeightForWidth())
        self.SecondFrame.setSizePolicy(sizePolicy)
        self.SecondFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SecondFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SecondFrame.setObjectName("SecondFrame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.SecondFrame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_5.addWidget(self.SecondFrame)
        self.frame_10 = QtWidgets.QFrame(self.LabDetails)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.verticalLayout_12.addWidget(self.LabDetails)
        self.verticalLayout_5.addWidget(self.LabReq)
        self.verticalLayout_2.addWidget(self.MainBody)
        self.Button = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button.sizePolicy().hasHeightForWidth())
        self.Button.setSizePolicy(sizePolicy)
        self.Button.setStyleSheet("QPushButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"     padding: 10px 20px;\n"
"    text-align: center;\n"
"    background-color: #2E6E65;\n"
"padding: 20px 20px;\n"
"}")
        self.Button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Button.setObjectName("Button")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Button)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ProceedButton = QtWidgets.QPushButton(self.Button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProceedButton.sizePolicy().hasHeightForWidth())
        self.ProceedButton.setSizePolicy(sizePolicy)
        self.ProceedButton.setMaximumSize(QtCore.QSize(250, 60))
        self.ProceedButton.setIconSize(QtCore.QSize(40, 40))
        self.ProceedButton.setObjectName("ProceedButton")
        self.horizontalLayout_11.addWidget(self.ProceedButton)
        self.verticalLayout_2.addWidget(self.Button, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.MainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "COVACHA DIAGNOSTIC SYSTEM"))
        self.Subheader.setText(_translate("MainWindow", "Check Up Form"))
        self.Label.setText(_translate("MainWindow", "Patient ID"))
        self.PatID.setText(_translate("MainWindow", "1000023"))
        self.Label_2.setText(_translate("MainWindow", "Patient Name"))
        self.PatName.setText(_translate("MainWindow", "Rondina, Roy Adrian"))
        self.label_3.setText(_translate("MainWindow", "Date Of Birth"))
        self.Dob.setText(_translate("MainWindow", "Jan. 18, 2005"))
        self.label.setText(_translate("MainWindow", "Age"))
        self.Age.setText(_translate("MainWindow", "20"))
        self.label_4.setText(_translate("MainWindow", "Gender"))
        self.PatGender.setText(_translate("MainWindow", "Male"))
        self.weg.setText(_translate("MainWindow", "Check-Up ID"))
        self.CheckID.setText(_translate("MainWindow", "121323-002"))
        self.Type_2.setText(_translate("MainWindow", "Check Up Type"))
        self.Type.setText(_translate("MainWindow", "New Check Up"))
        self.BPLabel_2.setText(_translate("MainWindow", "Blood Pressure:"))
        self.TempLabel_2.setText(_translate("MainWindow", "Temperature: "))
        self.BP.setText(_translate("MainWindow", "TextLabel"))
        self.Temperature.setText(_translate("MainWindow", "TextLabel"))
        self.WeightLabel_2.setText(_translate("MainWindow", "Weight:"))
        self.HeightLabel_2.setText(_translate("MainWindow", "Height:"))
        self.Weight.setText(_translate("MainWindow", "TextLabel"))
        self.Height.setText(_translate("MainWindow", "TextLabel"))
        self.LabLabel.setText(_translate("MainWindow", "Laboratory Request "))
        self.ProceedButton.setText(_translate("MainWindow", "Proceed Check Up"))
