# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doctor_Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Doctor_Dashboard(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1227, 809)
        Form.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 17pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"#User, #UserSpecialty {\n"
"    color: #F4F7ED;\n"
"}\n"
"#DoctorSidePanel {\n"
"     background-color: #2E6E65;\n"
"}\n"
"\n"
"#RecentText {\n"
"    color: #F4F7ED;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DashBoardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashBoardButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashBoardButton.setIcon(icon)
        self.DashBoardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashBoardButton.setObjectName("DashBoardButton")
        self.verticalLayout.addWidget(self.DashBoardButton)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.MainButtons = QtWidgets.QVBoxLayout()
        self.MainButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons.setSpacing(20)
        self.MainButtons.setObjectName("MainButtons")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons.addWidget(self.DashboardButton)
        self.CheckUpButton = QtWidgets.QPushButton(self.NavBar)
        self.CheckUpButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/square-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckUpButton.setIcon(icon2)
        self.CheckUpButton.setIconSize(QtCore.QSize(40, 40))
        self.CheckUpButton.setObjectName("CheckUpButton")
        self.MainButtons.addWidget(self.CheckUpButton)
        self.RecordsButton = QtWidgets.QPushButton(self.NavBar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecordsButton.setIcon(icon3)
        self.RecordsButton.setIconSize(QtCore.QSize(40, 40))
        self.RecordsButton.setObjectName("RecordsButton")
        self.MainButtons.addWidget(self.RecordsButton)
        self.verticalLayout.addLayout(self.MainButtons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.NavBar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 100px;\n"
"    background: white;\n"
"}\n"
"\n"
"#TotalPatientOverview {\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"    color: #2E6E65;\n"
"    text-align: left top;\n"
"}\n"
"\n"
"#DiagnosisButton, #TEXT {\n"
"    background-color: #2E6E65;\n"
"    text-align: left top;\n"
"}\n"
"\n"
"#InterfaceTitle  {\n"
"    font-size: 40px;\n"
"}\n"
"\n"
"#DoctorSidePanel {\n"
"    background-color: #b9cec4;\n"
"}\n"
"\n"
"#SeeAllButton {\n"
"    text-align: right;\n"
"    color: #2E6E65;\n"
"    font-size: 18px\n"
"}\n"
"\n"
"#Line {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"#RecentText {\n"
"    color: #2E6E65;\n"
"}\n"
"\n"
"#User {\n"
"    color: #2B3752;\n"
"}\n"
"\n"
"#UserSpecialty {\n"
"    color: #2B3752;\n"
"    font-size: 14px;\n"
"    text-align: center;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QFrame#Histories QFrame {\n"
"    background-color: #8fb1a8;\n"
"}\n"
"\n"
"#TotalLabel {\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"#TotalInfo {\n"
"    color: #2b3752;\n"
"    font-size: 40px;\n"
"}\n"
"\n"
"#TotalDescription {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#AddCheckUpButton {\n"
"    text-align: center;\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MainBodyContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Body = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Body.sizePolicy().hasHeightForWidth())
        self.Body.setSizePolicy(sizePolicy)
        self.Body.setMinimumSize(QtCore.QSize(0, 0))
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Body)
        self.verticalLayout_6.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Header = QtWidgets.QFrame(self.Body)
        self.Header.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"    padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InterfaceTitle = QtWidgets.QLabel(self.Header)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_3.addWidget(self.InterfaceTitle)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_5.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_3.addLayout(self.UserPanel)
        self.verticalLayout_6.addWidget(self.Header)
        self.ShortcutButtons = QtWidgets.QFrame(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShortcutButtons.sizePolicy().hasHeightForWidth())
        self.ShortcutButtons.setSizePolicy(sizePolicy)
        self.ShortcutButtons.setMinimumSize(QtCore.QSize(150, 150))
        self.ShortcutButtons.setStyleSheet("#AddCheckUpButton, #AddTransactionButton {\n"
"    text-align: center;\n"
"}\n"
"\n"
"#TotalPatient, #DayFrame {\n"
"    border: 2px solid  #2e6e65;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#Review {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#Total, #Time {\n"
"    color: #2b3752;\n"
"    font-size: 33px;\n"
"}\n"
"\n"
"#Day {\n"
"    color: #2e6e65;\n"
"    font-weight: 300;\n"
"    font-size: 16px\n"
"}\n"
"\n"
"")
        self.ShortcutButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ShortcutButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ShortcutButtons.setObjectName("ShortcutButtons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ShortcutButtons)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.AcceptCheckUp = QtWidgets.QPushButton(self.ShortcutButtons)
        self.AcceptCheckUp.setMinimumSize(QtCore.QSize(0, 60))
        self.AcceptCheckUp.setMaximumSize(QtCore.QSize(16777215, 60))
        self.AcceptCheckUp.setStyleSheet("QPushButton{\n"
"    text-align: center;\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/file-plus-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AcceptCheckUp.setIcon(icon5)
        self.AcceptCheckUp.setIconSize(QtCore.QSize(40, 40))
        self.AcceptCheckUp.setObjectName("AcceptCheckUp")
        self.horizontalLayout_4.addWidget(self.AcceptCheckUp, 0, QtCore.Qt.AlignBottom)
        self.TotalPatient = QtWidgets.QFrame(self.ShortcutButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalPatient.sizePolicy().hasHeightForWidth())
        self.TotalPatient.setSizePolicy(sizePolicy)
        self.TotalPatient.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TotalPatient.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TotalPatient.setObjectName("TotalPatient")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.TotalPatient)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.TotalPatient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("#pushButton_6 {\n"
"    color: black;\n"
"    background-color: transparent;\n"
"}")
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/file-user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.TotalLabel = QtWidgets.QLabel(self.TotalPatient)
        self.TotalLabel.setObjectName("TotalLabel")
        self.horizontalLayout_7.addWidget(self.TotalLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.Total = QtWidgets.QLabel(self.TotalPatient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Total.sizePolicy().hasHeightForWidth())
        self.Total.setSizePolicy(sizePolicy)
        self.Total.setObjectName("Total")
        self.verticalLayout_8.addWidget(self.Total)
        self.horizontalLayout_4.addWidget(self.TotalPatient)
        self.DayFrame = QtWidgets.QFrame(self.ShortcutButtons)
        self.DayFrame.setMinimumSize(QtCore.QSize(205, 121))
        self.DayFrame.setStyleSheet("#AddCheckUpButton, #AddTransactionButton {\n"
"    text-align: center;\n"
"}\n"
"\n"
"#TotalPatient, #DayFrame {\n"
"    border: 2px solid  #2e6e65;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#Review {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#Total, #Time {\n"
"    color: #2b3752;\n"
"    font-size: 33px;\n"
"}\n"
"\n"
"#Day {\n"
"    color: #2e6e65;\n"
"    font-weight: 300;\n"
"    font-size: 16px\n"
"}\n"
"\n"
"")
        self.DayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DayFrame.setObjectName("DayFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.DayFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Time = QtWidgets.QLabel(self.DayFrame)
        self.Time.setObjectName("Time")
        self.verticalLayout_9.addWidget(self.Time, 0, QtCore.Qt.AlignRight)
        self.Day = QtWidgets.QLabel(self.DayFrame)
        self.Day.setObjectName("Day")
        self.verticalLayout_9.addWidget(self.Day, 0, QtCore.Qt.AlignRight)
        self.Month = QtWidgets.QLabel(self.DayFrame)
        self.Month.setObjectName("Month")
        self.verticalLayout_9.addWidget(self.Month, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addWidget(self.DayFrame)
        self.verticalLayout_6.addWidget(self.ShortcutButtons, 0, QtCore.Qt.AlignRight)
        self.MainBody = QtWidgets.QFrame(self.Body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_7.setContentsMargins(9, 10, 0, 30)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LabelHolder = QtWidgets.QHBoxLayout()
        self.LabelHolder.setObjectName("LabelHolder")
        self.PatRec = QtWidgets.QLabel(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatRec.sizePolicy().hasHeightForWidth())
        self.PatRec.setSizePolicy(sizePolicy)
        self.PatRec.setObjectName("PatRec")
        self.LabelHolder.addWidget(self.PatRec)
        self.SeeAllButton = QtWidgets.QPushButton(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SeeAllButton.sizePolicy().hasHeightForWidth())
        self.SeeAllButton.setSizePolicy(sizePolicy)
        self.SeeAllButton.setText("")
        self.SeeAllButton.setObjectName("SeeAllButton")
        self.LabelHolder.addWidget(self.SeeAllButton)
        self.verticalLayout_7.addLayout(self.LabelHolder)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.PatientDetails = QtWidgets.QTableWidget(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatientDetails.sizePolicy().hasHeightForWidth())
        self.PatientDetails.setSizePolicy(sizePolicy)
        self.PatientDetails.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font: 16pt \"Lexend\";\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 18px \"Lexend Medium\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.PatientDetails.setWordWrap(True)
        self.PatientDetails.setObjectName("PatientDetails")
        self.PatientDetails.setColumnCount(3)
        self.PatientDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PatientDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PatientDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PatientDetails.setHorizontalHeaderItem(2, item)
        self.PatientDetails.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.PatientDetails)
        self.verticalLayout_6.addWidget(self.MainBody)
        self.horizontalLayout_2.addWidget(self.Body)
        self.horizontalLayout.addWidget(self.MainBodyContainer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.DashboardButton.setText(_translate("Form", "Dashboard"))
        self.CheckUpButton.setText(_translate("Form", "Check Up"))
        self.RecordsButton.setText(_translate("Form", "Records"))
        self.pushButton_4.setText(_translate("Form", "Logout"))
        self.InterfaceTitle.setText(_translate("Form", "Dashboard"))
        self.UserName.setText(_translate("Form", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("Form", "Doctor"))
        self.AcceptCheckUp.setText(_translate("Form", "Accept Check Up"))
        self.TotalLabel.setText(_translate("Form", "Total Patient"))
        self.Total.setText(_translate("Form", "0000"))
        self.Time.setText(_translate("Form", "00:00 AM"))
        self.Day.setText(_translate("Form", "Sunday"))
        self.Month.setText(_translate("Form", "Month 00, 2025"))
        self.PatRec.setText(_translate("Form", "Check Ups"))
        item = self.PatientDetails.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Check Up ID"))
        item = self.PatientDetails.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Patient ID"))
        item = self.PatientDetails.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Name"))
