# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doctor_CheckUpList.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Doctor_CheckUpList(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1074, 748)
        Form.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 17pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65;\n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DashBoardButton_2 = QtWidgets.QPushButton(self.NavBar)
        self.DashBoardButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashBoardButton_2.setIcon(icon)
        self.DashBoardButton_2.setIconSize(QtCore.QSize(40, 40))
        self.DashBoardButton_2.setObjectName("DashBoardButton_2")
        self.verticalLayout_3.addWidget(self.DashBoardButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.MainButtons_2 = QtWidgets.QVBoxLayout()
        self.MainButtons_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons_2.setSpacing(20)
        self.MainButtons_2.setObjectName("MainButtons_2")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons_2.addWidget(self.DashboardButton)
        self.CheckUpButton = QtWidgets.QPushButton(self.NavBar)
        self.CheckUpButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/square-pen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckUpButton.setIcon(icon2)
        self.CheckUpButton.setIconSize(QtCore.QSize(40, 40))
        self.CheckUpButton.setObjectName("CheckUpButton")
        self.MainButtons_2.addWidget(self.CheckUpButton)
        self.RecordsButton = QtWidgets.QPushButton(self.NavBar)
        self.RecordsButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecordsButton.setIcon(icon3)
        self.RecordsButton.setIconSize(QtCore.QSize(40, 40))
        self.RecordsButton.setObjectName("RecordsButton")
        self.MainButtons_2.addWidget(self.RecordsButton)
        self.verticalLayout_3.addLayout(self.MainButtons_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.NavBar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(Form)
        self.MainBodyContainer.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.Header)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InterfaceTitle = QtWidgets.QLabel(self.widget_3)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_2.addWidget(self.InterfaceTitle, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.widget_3)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setContentsMargins(-1, -1, 7, -1)
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_6.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_6.addLayout(self.UserPanel)
        self.verticalLayout_5.addWidget(self.Header)
        self.MainBody = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setStyleSheet("#Searchbar {\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"    text-align: center;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #b5cecb;\n"
"    font-size: 15px;\n"
"    color: #1b3b3a;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #2E6E65;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"")
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_2.setContentsMargins(20, 0, 20, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SearchBarContainer = QtWidgets.QFrame(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBarContainer.sizePolicy().hasHeightForWidth())
        self.SearchBarContainer.setSizePolicy(sizePolicy)
        self.SearchBarContainer.setMaximumSize(QtCore.QSize(16777215, 70))
        self.SearchBarContainer.setStyleSheet("QComboBox {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/lucide/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;  \n"
"    font: 300 12pt \"Lexend Light\";\n"
"}")
        self.SearchBarContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchBarContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchBarContainer.setObjectName("SearchBarContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SearchBarContainer)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SearchBar = QtWidgets.QWidget(self.SearchBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBar.sizePolicy().hasHeightForWidth())
        self.SearchBar.setSizePolicy(sizePolicy)
        self.SearchBar.setMinimumSize(QtCore.QSize(290, 0))
        self.SearchBar.setStyleSheet("#SearchBar {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"}\n"
"#Search{\n"
"    background-color: transparent ;\n"
"    font: 300 14pt \"Lexend Light\";\n"
"}")
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SearchBar)
        self.horizontalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Icon = QtWidgets.QPushButton(self.SearchBar)
        self.Icon.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon5)
        self.Icon.setIconSize(QtCore.QSize(35, 35))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_3.addWidget(self.Icon)
        self.Search = QtWidgets.QLineEdit(self.SearchBar)
        self.Search.setObjectName("Search")
        self.horizontalLayout_3.addWidget(self.Search)
        self.horizontalLayout_4.addWidget(self.SearchBar)
        self.StatusBox = QtWidgets.QComboBox(self.SearchBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusBox.sizePolicy().hasHeightForWidth())
        self.StatusBox.setSizePolicy(sizePolicy)
        self.StatusBox.setMinimumSize(QtCore.QSize(180, 0))
        self.StatusBox.setStyleSheet("")
        self.StatusBox.setEditable(False)
        self.StatusBox.setObjectName("StatusBox")
        self.StatusBox.addItem("")
        self.horizontalLayout_4.addWidget(self.StatusBox)
        self.TypeBox = QtWidgets.QComboBox(self.SearchBarContainer)
        self.TypeBox.setMinimumSize(QtCore.QSize(180, 0))
        self.TypeBox.setStyleSheet("")
        self.TypeBox.setObjectName("TypeBox")
        self.TypeBox.addItem("")
        self.horizontalLayout_4.addWidget(self.TypeBox)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.SearchBarContainer)
        self.widget = QtWidgets.QWidget(self.MainBody)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 678, 581))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.DoneTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.DoneTable.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font: 16pt \"Lexend\";\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 18px \"Lexend Medium\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.DoneTable.setObjectName("DoneTable")
        self.DoneTable.setColumnCount(4)
        self.DoneTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(3, item)
        self.DoneTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.DoneTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(110, 0))
        self.widget_2.setStyleSheet("QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color:  #2E6E65;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    color: #F4F7ED;\n"
"    text-align: center;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ViewPatientButton = QtWidgets.QPushButton(self.widget_2)
        self.ViewPatientButton.setObjectName("ViewPatientButton")
        self.verticalLayout.addWidget(self.ViewPatientButton)
        self.horizontalLayout_5.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_5.addWidget(self.MainBody)
        self.horizontalLayout.addWidget(self.MainBodyContainer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.DashboardButton.setText(_translate("Form", " Dashboard"))
        self.CheckUpButton.setText(_translate("Form", " Check Up"))
        self.RecordsButton.setText(_translate("Form", " Records"))
        self.pushButton_10.setText(_translate("Form", " Logout"))
        self.InterfaceTitle.setText(_translate("Form", "Records"))
        self.UserName.setText(_translate("Form", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("Form", "Doctor"))
        self.StatusBox.setItemText(0, _translate("Form", "Status"))
        self.TypeBox.setItemText(0, _translate("Form", "Type"))
        item = self.DoneTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Patient ID"))
        item = self.DoneTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.DoneTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Recent Diagnosis"))
        item = self.DoneTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Last Diagnosed"))
        self.ViewPatientButton.setText(_translate("Form", "View"))
