# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 805)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(1150, 805))
        MainWindow.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"#LogInPanel {\n"
"    background-color: #2E6E65;\n"
"}\n"
"#Login{\n"
"    background-color: #F4F7ED;\n"
"    border-radius: 20px;\n"
"}\n"
"#SystemTitle{\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    padding: 0px 10px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    qproperty-wordWrap: true;\n"
"}\n"
"QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    padding: 5px 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4C9F8C;\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"    text-align: center;\n"
"    font-size: 20px;\n"
"    background-color: #F4F7ED;\n"
"    padding: 2px 2px;\n"
"}\n"
"#ForgotPassword {\n"
"    color: #2E6E65;\n"
"    font: 300 10pt \"Lexend Light\";\n"
"}\n"
"")
        self.LogInPanel = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogInPanel.sizePolicy().hasHeightForWidth())
        self.LogInPanel.setSizePolicy(sizePolicy)
        self.LogInPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.LogInPanel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LogInPanel.setBaseSize(QtCore.QSize(0, 0))
        self.LogInPanel.setObjectName("LogInPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LogInPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Login = QtWidgets.QWidget(self.LogInPanel)
        self.Login.setMinimumSize(QtCore.QSize(400, 410))
        self.Login.setMaximumSize(QtCore.QSize(400, 410))
        self.Login.setObjectName("Login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Login)
        self.verticalLayout_2.setContentsMargins(15, 30, 15, 30)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SystemTitle = QtWidgets.QLabel(self.Login)
        self.SystemTitle.setEnabled(False)
        self.SystemTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SystemTitle.setStyleSheet("")
        self.SystemTitle.setWordWrap(True)
        self.SystemTitle.setObjectName("SystemTitle")
        self.verticalLayout_2.addWidget(self.SystemTitle, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Description1 = QtWidgets.QLabel(self.Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Description1.sizePolicy().hasHeightForWidth())
        self.Description1.setSizePolicy(sizePolicy)
        self.Description1.setStyleSheet("QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color:  #2E6E65;\n"
"    background: transparent;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.Description1.setObjectName("Description1")
        self.verticalLayout_2.addWidget(self.Description1)
        self.Description2 = QtWidgets.QLabel(self.Login)
        self.Description2.setStyleSheet("QLabel {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 12px;\n"
"    color:  #2E6E65;\n"
"    background: transparent;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.Description2.setObjectName("Description2")
        self.verticalLayout_2.addWidget(self.Description2)
        self.UserIDInput = QtWidgets.QLineEdit(self.Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserIDInput.sizePolicy().hasHeightForWidth())
        self.UserIDInput.setSizePolicy(sizePolicy)
        self.UserIDInput.setMinimumSize(QtCore.QSize(0, 45))
        self.UserIDInput.setMaximumSize(QtCore.QSize(16777215, 45))
        self.UserIDInput.setStyleSheet("")
        self.UserIDInput.setObjectName("UserIDInput")
        self.verticalLayout_2.addWidget(self.UserIDInput)
        self.PasswordInput = QtWidgets.QLineEdit(self.Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswordInput.sizePolicy().hasHeightForWidth())
        self.PasswordInput.setSizePolicy(sizePolicy)
        self.PasswordInput.setMinimumSize(QtCore.QSize(0, 45))
        self.PasswordInput.setMaximumSize(QtCore.QSize(16777215, 45))
        self.PasswordInput.setStyleSheet("")
        self.PasswordInput.setObjectName("PasswordInput")
        self.verticalLayout_2.addWidget(self.PasswordInput, 0, QtCore.Qt.AlignVCenter)
        self.SignInButton = QtWidgets.QPushButton(self.Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignInButton.sizePolicy().hasHeightForWidth())
        self.SignInButton.setSizePolicy(sizePolicy)
        self.SignInButton.setMinimumSize(QtCore.QSize(0, 45))
        self.SignInButton.setMaximumSize(QtCore.QSize(16777215, 45))
        self.SignInButton.setStyleSheet("QPushButton {\n"
"    background-color: #2E6E65;\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}")
        self.SignInButton.setObjectName("SignInButton")
        self.verticalLayout_2.addWidget(self.SignInButton)
        self.verticalLayout.addWidget(self.Login, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.LogInPanel)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SystemTitle.setText(_translate("MainWindow", "COVACHA Diagnostic Services"))
        self.Description1.setText(_translate("MainWindow", "Log in to your account"))
        self.Description2.setText(_translate("MainWindow", "Please enter your details to continue"))
        self.UserIDInput.setText(_translate("MainWindow", "USER ID"))
        self.UserIDInput.setProperty("html", _translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lexend\'; font-size:16pt; color:#2b3752;\">User ID</span></p></body></html>"))
        self.PasswordInput.setText(_translate("MainWindow", "PASSWORD"))
        self.PasswordInput.setProperty("html", _translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lexend\'; font-size:16pt; color:#2b3752;\">Password</span></p></body></html>"))
        self.SignInButton.setText(_translate("MainWindow", "Sign In"))
