# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Staff_Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.UserID = QtWidgets.QLineEdit(Dialog)
        self.UserID.setGeometry(QtCore.QRect(30, 30, 201, 41))
        self.UserID.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"    font-size: 24px;\n"
"    padding-left: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.UserID.setObjectName("UserID")
        self.UserName = QtWidgets.QLineEdit(Dialog)
        self.UserName.setGeometry(QtCore.QRect(30, 90, 351, 41))
        self.UserName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"    font-size: 24px;\n"
"    padding-left: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.UserName.setObjectName("UserName")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(80, 160, 121, 71))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:700;\">STAFF</span></p></body></html>"))
