# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Staff_Records.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Staff_Records(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1137, 737)
        Form.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;    \n"
"    font-size: 25px;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65; \n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DashBoardButton_2 = QtWidgets.QPushButton(self.NavBar)
        self.DashBoardButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashBoardButton_2.setIcon(icon)
        self.DashBoardButton_2.setIconSize(QtCore.QSize(40, 40))
        self.DashBoardButton_2.setObjectName("DashBoardButton_2")
        self.verticalLayout_3.addWidget(self.DashBoardButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.MainButtons_2 = QtWidgets.QVBoxLayout()
        self.MainButtons_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons_2.setSpacing(20)
        self.MainButtons_2.setObjectName("MainButtons_2")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons_2.addWidget(self.DashboardButton)
        self.RecordsButton = QtWidgets.QPushButton(self.NavBar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecordsButton.setIcon(icon2)
        self.RecordsButton.setIconSize(QtCore.QSize(40, 40))
        self.RecordsButton.setObjectName("RecordsButton")
        self.MainButtons_2.addWidget(self.RecordsButton)
        self.TransactionsButton = QtWidgets.QPushButton(self.NavBar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionsButton.setIcon(icon3)
        self.TransactionsButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionsButton.setObjectName("TransactionsButton")
        self.MainButtons_2.addWidget(self.TransactionsButton)
        self.LabButton = QtWidgets.QPushButton(self.NavBar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/test-tubes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LabButton.setIcon(icon4)
        self.LabButton.setIconSize(QtCore.QSize(40, 40))
        self.LabButton.setObjectName("LabButton")
        self.MainButtons_2.addWidget(self.LabButton)
        self.verticalLayout_3.addLayout(self.MainButtons_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.NavBar)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/user-round-cog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.NavBar)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QFrame(Form)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"#Header {\n"
"    padding: 20px 20px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 25px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 40px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"\n"
"\n"
"")
        self.MainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InterfaceTitle = QtWidgets.QLabel(self.Header)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_2.addWidget(self.InterfaceTitle)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_6.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_2.addLayout(self.UserPanel)
        self.verticalLayout_5.addWidget(self.Header)
        self.MainBody = QtWidgets.QFrame(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setStyleSheet("#Searchbar {\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 15px;\n"
"    text-align: center;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#AddButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_7.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SearchBarContainer = QtWidgets.QFrame(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBarContainer.sizePolicy().hasHeightForWidth())
        self.SearchBarContainer.setSizePolicy(sizePolicy)
        self.SearchBarContainer.setMaximumSize(QtCore.QSize(16777215, 70))
        self.SearchBarContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SearchBarContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SearchBarContainer.setObjectName("SearchBarContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SearchBarContainer)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SearchBar = QtWidgets.QWidget(self.SearchBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchBar.sizePolicy().hasHeightForWidth())
        self.SearchBar.setSizePolicy(sizePolicy)
        self.SearchBar.setMinimumSize(QtCore.QSize(0, 0))
        self.SearchBar.setMaximumSize(QtCore.QSize(500, 16777215))
        self.SearchBar.setStyleSheet("#SearchBar {\n"
"    background-color: #F4F7ED;\n"
"    border: 2px solid #2E6E65; \n"
"    border-radius: 15px;\n"
"}\n"
"#Search{\n"
"    background-color: transparent ;\n"
"    font: 300 14pt \"Lexend Light\";\n"
"}")
        self.SearchBar.setObjectName("SearchBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SearchBar)
        self.horizontalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Icon = QtWidgets.QPushButton(self.SearchBar)
        self.Icon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Icon.setIcon(icon7)
        self.Icon.setIconSize(QtCore.QSize(40, 30))
        self.Icon.setObjectName("Icon")
        self.horizontalLayout_3.addWidget(self.Icon)
        self.Search = QtWidgets.QLineEdit(self.SearchBar)
        self.Search.setObjectName("Search")
        self.horizontalLayout_3.addWidget(self.Search)
        self.horizontalLayout_4.addWidget(self.SearchBar)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.StatusBox = QtWidgets.QComboBox(self.SearchBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusBox.sizePolicy().hasHeightForWidth())
        self.StatusBox.setSizePolicy(sizePolicy)
        self.StatusBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.StatusBox.setStyleSheet("QComboBox {\n"
"    background-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;  \n"
"    font: 300 12pt \"Lexend Light\";\n"
"}")
        self.StatusBox.setEditable(False)
        self.StatusBox.setObjectName("StatusBox")
        self.StatusBox.addItem("")
        self.horizontalLayout_4.addWidget(self.StatusBox)
        self.TypeBox = QtWidgets.QComboBox(self.SearchBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TypeBox.sizePolicy().hasHeightForWidth())
        self.TypeBox.setSizePolicy(sizePolicy)
        self.TypeBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TypeBox.setStyleSheet("QComboBox {\n"
"    background-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;  \n"
"    font: 300 12pt \"Lexend Light\";\n"
"}")
        self.TypeBox.setObjectName("TypeBox")
        self.TypeBox.addItem("")
        self.horizontalLayout_4.addWidget(self.TypeBox)
        self.DateBox = QtWidgets.QComboBox(self.SearchBarContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateBox.sizePolicy().hasHeightForWidth())
        self.DateBox.setSizePolicy(sizePolicy)
        self.DateBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DateBox.setStyleSheet("QComboBox {\n"
"    background-color: #D9E4DC;\n"
"    border: 2px solid #2E6E65;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    font: 300 12pt \"Lexend Light\";\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 1px solid #2E6E65;\n"
"    background-color: #D9E4DC;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #F4F7ED;\n"
"    selection-background-color: #CCE3D0;\n"
"    border: 1px solid #2E6E65;\n"
"    border-radius: 2px;\n"
"    outline: 0;  \n"
"    font: 300 12pt \"Lexend Light\";\n"
"}")
        self.DateBox.setObjectName("DateBox")
        self.DateBox.addItem("")
        self.horizontalLayout_4.addWidget(self.DateBox)
        self.AddButton = QtWidgets.QPushButton(self.SearchBarContainer)
        self.AddButton.setMinimumSize(QtCore.QSize(0, 50))
        self.AddButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout_4.addWidget(self.AddButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.SearchBarContainer)
        self.DoneTable = QtWidgets.QTableWidget(self.MainBody)
        self.DoneTable.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font:500 16pt \"Satoshi\";\n"
"    color: #2B3752;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 700 15pt \"Satoshi\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.DoneTable.setObjectName("DoneTable")
        self.DoneTable.setColumnCount(4)
        self.DoneTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DoneTable.setHorizontalHeaderItem(3, item)
        self.DoneTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.DoneTable)
        self.verticalLayout_5.addWidget(self.MainBody)
        self.horizontalLayout.addWidget(self.MainBodyContainer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.DashboardButton.setText(_translate("Form", "Dashboard"))
        self.RecordsButton.setText(_translate("Form", "Records"))
        self.TransactionsButton.setText(_translate("Form", "Transactions"))
        self.LabButton.setText(_translate("Form", "Lab Request"))
        self.pushButton_9.setText(_translate("Form", "Settings"))
        self.pushButton_10.setText(_translate("Form", "Logout"))
        self.InterfaceTitle.setText(_translate("Form", "Records"))
        self.UserName.setText(_translate("Form", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("Form", "Nurse"))
        self.StatusBox.setItemText(0, _translate("Form", "Status"))
        self.TypeBox.setItemText(0, _translate("Form", "Type"))
        self.DateBox.setItemText(0, _translate("Form", "Date"))
        self.AddButton.setText(_translate("Form", "Add Check Up"))
        item = self.DoneTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Patient ID"))
        item = self.DoneTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.DoneTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Diagnosis"))
        item = self.DoneTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Date Diagnosed"))

