# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Staff_Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Staff_Dashboard(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1134, 805)
        Form.setStyleSheet("*{\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"}\n"
"QPushButton {\n"
"    font: 900 17pt \"Satoshi Black\";\n"
"    background-color: transparent;\n"
"     border-radius: 10px;\n"
"    font-weight: bold;\n"
"    color: #F4F7ED;\n"
"    text-align: left;\n"
"    padding: 5px 5px;\n"
"}\n"
"#NavBar {\n"
"    background-color: #2E6E65; \n"
"}\n"
"QLabel {\n"
"    font: 900 10pt \"Satoshi Black\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2E6E65;\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    qproperty-wordWrap: true;\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavBar = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NavBar.sizePolicy().hasHeightForWidth())
        self.NavBar.setSizePolicy(sizePolicy)
        self.NavBar.setObjectName("NavBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.NavBar)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DashBoardButton_2 = QtWidgets.QPushButton(self.NavBar)
        self.DashBoardButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashBoardButton_2.setIcon(icon)
        self.DashBoardButton_2.setIconSize(QtCore.QSize(40, 40))
        self.DashBoardButton_2.setObjectName("DashBoardButton_2")
        self.verticalLayout_3.addWidget(self.DashBoardButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.MainButtons_2 = QtWidgets.QVBoxLayout()
        self.MainButtons_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MainButtons_2.setSpacing(20)
        self.MainButtons_2.setObjectName("MainButtons_2")
        self.DashboardButton = QtWidgets.QPushButton(self.NavBar)
        self.DashboardButton.setStyleSheet("QPushButton{\n"
"    font: 900 20pt \"Satoshi Black\";    \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/layout-dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DashboardButton.setIcon(icon1)
        self.DashboardButton.setIconSize(QtCore.QSize(40, 40))
        self.DashboardButton.setObjectName("DashboardButton")
        self.MainButtons_2.addWidget(self.DashboardButton)
        self.TransactionsButton = QtWidgets.QPushButton(self.NavBar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/tickets.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TransactionsButton.setIcon(icon2)
        self.TransactionsButton.setIconSize(QtCore.QSize(40, 40))
        self.TransactionsButton.setObjectName("TransactionsButton")
        self.MainButtons_2.addWidget(self.TransactionsButton)
        self.LabButton = QtWidgets.QPushButton(self.NavBar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/test-tubes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LabButton.setIcon(icon3)
        self.LabButton.setIconSize(QtCore.QSize(40, 40))
        self.LabButton.setObjectName("LabButton")
        self.MainButtons_2.addWidget(self.LabButton)
        self.verticalLayout_3.addLayout(self.MainButtons_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LogOutButton = QtWidgets.QPushButton(self.NavBar)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LogOutButton.setIcon(icon4)
        self.LogOutButton.setIconSize(QtCore.QSize(40, 40))
        self.LogOutButton.setObjectName("LogOutButton")
        self.verticalLayout_4.addWidget(self.LogOutButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.NavBar)
        self.MainBodyContainer = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBodyContainer.sizePolicy().hasHeightForWidth())
        self.MainBodyContainer.setSizePolicy(sizePolicy)
        self.MainBodyContainer.setStyleSheet("#MainBodyContainer {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"#Header {\n"
"    padding: 20px 20px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 25px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 40px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2E6E65; \n"
"    font-size: 15px;\n"
"    color: #1b3b3a; \n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 1px solid #2E6E65; \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2e6e65;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.MainBodyContainer.setObjectName("MainBodyContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainBodyContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.MainBodyContainer)
        self.Header.setStyleSheet("#Header {\n"
"    padding: 10px 20px;\n"
"    padding-top: 15px;\n"
"}\n"
"QLabel {\n"
"    padding: 0px; \n"
"}\n"
"#UserType {\n"
"    font: 300 10pt \"Lexend Light\";\n"
"    font-size: 15px;\n"
"    color: #2B3752;\n"
"}\n"
"#UserName {\n"
"    font: 600 10pt \"Lexend SemiBold\";\n"
"    font-size: 20px;\n"
"    color: #2B3752;\n"
"}\n"
"#InterfaceTitle{\n"
"    font-size: 35px;\n"
"}\n"
"QGraphicsView {\n"
"    border: 2px solid #ccc; \n"
"    border-radius: 25px;\n"
"    background: white; \n"
"}")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.InterfaceTitle = QtWidgets.QLabel(self.Header)
        self.InterfaceTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InterfaceTitle.setAlignment(QtCore.Qt.AlignLeading)
        self.InterfaceTitle.setObjectName("InterfaceTitle")
        self.horizontalLayout_2.addWidget(self.InterfaceTitle)
        self.UserPanel = QtWidgets.QHBoxLayout()
        self.UserPanel.setContentsMargins(-1, -1, 0, -1)
        self.UserPanel.setObjectName("UserPanel")
        self.UserInfo = QtWidgets.QVBoxLayout()
        self.UserInfo.setSpacing(0)
        self.UserInfo.setObjectName("UserInfo")
        self.UserName = QtWidgets.QLabel(self.Header)
        self.UserName.setAlignment(QtCore.Qt.AlignLeading)
        self.UserName.setObjectName("UserName")
        self.UserInfo.addWidget(self.UserName, 0, QtCore.Qt.AlignRight)
        self.UserType = QtWidgets.QLabel(self.Header)
        self.UserType.setAlignment(QtCore.Qt.AlignLeading)
        self.UserType.setObjectName("UserType")
        self.UserInfo.addWidget(self.UserType, 0, QtCore.Qt.AlignRight)
        self.UserPanel.addLayout(self.UserInfo)
        self.Profile = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Profile.sizePolicy().hasHeightForWidth())
        self.Profile.setSizePolicy(sizePolicy)
        self.Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Profile)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProfilePic = QtWidgets.QGraphicsView(self.Profile)
        self.ProfilePic.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfilePic.sizePolicy().hasHeightForWidth())
        self.ProfilePic.setSizePolicy(sizePolicy)
        self.ProfilePic.setMinimumSize(QtCore.QSize(0, 0))
        self.ProfilePic.setObjectName("ProfilePic")
        self.verticalLayout_5.addWidget(self.ProfilePic)
        self.UserPanel.addWidget(self.Profile)
        self.horizontalLayout_2.addLayout(self.UserPanel)
        self.verticalLayout.addWidget(self.Header)
        self.widget = QtWidgets.QWidget(self.MainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopOverview = QtWidgets.QWidget(self.widget)
        self.TopOverview.setStyleSheet("#AddCheckUpButton, #AddTransactionButton {\n"
"    text-align: center;\n"
"}\n"
"\n"
"#TotalPatient, #DayFrame {\n"
"    border: 2px solid  #2e6e65;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#Review {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#Total, #Time {\n"
"    color: #2b3752;\n"
"    font-size: 33px;\n"
"}\n"
"\n"
"#Day {\n"
"    color: #2e6e65;\n"
"    font-weight: 300;\n"
"    font-size: 16px\n"
"}\n"
"\n"
"")
        self.TopOverview.setObjectName("TopOverview")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TopOverview)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.AddCheckUpButton = QtWidgets.QPushButton(self.TopOverview)
        self.AddCheckUpButton.setMinimumSize(QtCore.QSize(0, 60))
        self.AddCheckUpButton.setMaximumSize(QtCore.QSize(16777215, 60))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/file-plus-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddCheckUpButton.setIcon(icon5)
        self.AddCheckUpButton.setIconSize(QtCore.QSize(40, 40))
        self.AddCheckUpButton.setObjectName("AddCheckUpButton")
        self.horizontalLayout_3.addWidget(self.AddCheckUpButton, 0, QtCore.Qt.AlignBottom)
        self.AddTransactionButton = QtWidgets.QPushButton(self.TopOverview)
        self.AddTransactionButton.setMinimumSize(QtCore.QSize(0, 60))
        self.AddTransactionButton.setMaximumSize(QtCore.QSize(16777215, 60))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/ticket-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddTransactionButton.setIcon(icon6)
        self.AddTransactionButton.setIconSize(QtCore.QSize(40, 40))
        self.AddTransactionButton.setObjectName("AddTransactionButton")
        self.horizontalLayout_3.addWidget(self.AddTransactionButton, 0, QtCore.Qt.AlignBottom)
        self.TotalPatient = QtWidgets.QFrame(self.TopOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalPatient.sizePolicy().hasHeightForWidth())
        self.TotalPatient.setSizePolicy(sizePolicy)
        self.TotalPatient.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TotalPatient.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TotalPatient.setObjectName("TotalPatient")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.TotalPatient)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.TotalPatient)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9, 0, QtCore.Qt.AlignBottom)
        self.Total = QtWidgets.QLabel(self.TotalPatient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Total.sizePolicy().hasHeightForWidth())
        self.Total.setSizePolicy(sizePolicy)
        self.Total.setObjectName("Total")
        self.verticalLayout_8.addWidget(self.Total)
        self.horizontalLayout_3.addWidget(self.TotalPatient, 0, QtCore.Qt.AlignBottom)
        self.DayFrame = QtWidgets.QFrame(self.TopOverview)
        self.DayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DayFrame.setObjectName("DayFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.DayFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Time = QtWidgets.QLabel(self.DayFrame)
        self.Time.setObjectName("Time")
        self.verticalLayout_9.addWidget(self.Time, 0, QtCore.Qt.AlignRight)
        self.Day = QtWidgets.QLabel(self.DayFrame)
        self.Day.setObjectName("Day")
        self.verticalLayout_9.addWidget(self.Day, 0, QtCore.Qt.AlignRight)
        self.Month = QtWidgets.QLabel(self.DayFrame)
        self.Month.setObjectName("Month")
        self.verticalLayout_9.addWidget(self.Month, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.DayFrame)
        self.verticalLayout_2.addWidget(self.TopOverview)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TableFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableFrame.sizePolicy().hasHeightForWidth())
        self.TableFrame.setSizePolicy(sizePolicy)
        self.TableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TableFrame.setObjectName("TableFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.TableFrame)
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.TableFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.scrollArea = QtWidgets.QScrollArea(self.TableFrame)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"     background: transparent;\n"
"     width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        background: #C0C0C0;\n"
"        border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: #A0A0A0;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"        background: none;\n"
"        border: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 816, 532))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PendingTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.PendingTable.setStyleSheet("QTableWidget {\n"
"    background-color: #F4F7ED;\n"
"    gridline-color: transparent;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #2E6E65;\n"
"}\n"
"QTableWidget::item {\n"
"    border: none;\n"
"    font: 16pt \"Lexend\";\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(46, 110, 101, 0.3);\n"
"}\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: #2E6E65;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font: 18px \"Lexend Medium\";\n"
"    border: 2px solid #2E6E65;\n"
"}")
        self.PendingTable.setObjectName("PendingTable")
        self.PendingTable.setColumnCount(3)
        self.PendingTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PendingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PendingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PendingTable.setHorizontalHeaderItem(2, item)
        self.PendingTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.PendingTable)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.LowerOverview = QtWidgets.QFrame(self.TableFrame)
        self.LowerOverview.setStyleSheet("#DiagnosisOverview {\n"
"    border: 2px solid  #2e6e65;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#AgeStageOverview{\n"
"    border: 2px solid  #2e6e65;\n"
"    border-radius: 15px; \n"
"}\n"
"\n"
"#ByDiagnosisLabel, #ByAgeStageLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#ChildLabel, #AdultLabel, #ElderlyLabel, #TotalLabel {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#ChildPercentage, #AdultPercentage, #ElderlyPercentage, #TotalPercentage {\n"
"    color: #2b3752;\n"
"}\n"
"\n"
"#Diagnosis1, #Diagnosis2, #Diagnosis3, #Diagnosis4 {\n"
"    color: #2b3752;\n"
"    font-weight: 300;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#DiagnosisPercentage1, #DiagnosisPercentage2, #DiagnosisPercentage3, #DiagnosisPercentage4 {\n"
"    color: #2b3752\n"
"}\n"
"\n"
"#frame, #frame_2, #frame_5, #frame_7, #frame_8, #frame_9, #frame_10 {\n"
"    background-color: #b9cec4;\n"
"    border-radius: 13px;\n"
"}")
        self.LowerOverview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LowerOverview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LowerOverview.setObjectName("LowerOverview")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.LowerOverview)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10.addWidget(self.LowerOverview)
        self.horizontalLayout_4.addWidget(self.TableFrame)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.MainBodyContainer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.DashboardButton.setText(_translate("Form", " Dashboard"))
        self.TransactionsButton.setText(_translate("Form", " Transactions"))
        self.LabButton.setText(_translate("Form", " Lab Request"))
        self.LogOutButton.setText(_translate("Form", "Logout"))
        self.InterfaceTitle.setText(_translate("Form", "Dashboard"))
        self.UserName.setText(_translate("Form", "Roy Adrian Rondina"))
        self.UserType.setText(_translate("Form", "Staff"))
        self.AddCheckUpButton.setText(_translate("Form", "Add Check Up"))
        self.AddTransactionButton.setText(_translate("Form", "Add Transaction"))
        self.label_9.setText(_translate("Form", "Total Patient"))
        self.Total.setText(_translate("Form", "0000"))
        self.Time.setText(_translate("Form", "00:00 AM"))
        self.Day.setText(_translate("Form", "Sunday"))
        self.Month.setText(_translate("Form", "Month 00, 2025"))
        self.label_2.setText(_translate("Form", "Pending Check Ups"))
        item = self.PendingTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Check up ID"))
        item = self.PendingTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Patient Name"))
        item = self.PendingTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Check Up Type"))
